# Generated by Django 3.1 on 2021-01-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.BigIntegerField()),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
