# Generated by Django 3.1 on 2021-01-31 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0003_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymousdonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zipcode', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('checksum_id', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regulardonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('checksum_id', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
